# Generated by Django 2.0.8 on 2019-03-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cry_analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='')),
            ],
        ),
    ]
